### ISSUE TITLE
 关于反编译

### ISSUE THREAD

**Issue by EzioL** [life2015/One#1]
是怎么反编译看到接口的..

**Comment by life2015** [comment]
google上弄到的接口，不是反编译得到的

**Comment by EzioL** [comment]
好吧好吧  可以分享一下吗

**Comment by life2015** [comment]
可以，不过版权是官方的哈哈

**Comment by life2015** [comment]
https://github.com/anpho/one3.0/wiki/API清单

**Comment by EzioL** [comment]
谢谢

**Comment by EzioL** [comment]
再次请问一下  电影列表的 分页 请求   第二页 怎么拿到  （ http://v3.wufazhuce.com:8000/api/movie/list/0）

**Comment by life2015** [comment]
我没有实现那个功能...后来就没有做下去
